---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: GetDeploymentConfigs
    inherits: 
    description: 
  fields:
  - meth1:
      value: get_deployment_configs
