---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - cluster_url:
      value: https://openshift.kenscloud.io
  - no_verify_ssl:
      value: 'true'
  - client_cert_location:
      value: "/root/.pki/hamastercert.pem"
  - client_key_location:
      value: "/root/.pki/hamasterkey.pem"
  - client_ca_cert_location:
      value: "/root/.pki/hamasterca.pem"
  - meth1:
      value: default
