---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - cluster_url:
      value: https://openshift.clustera.ocp.kenscloud.io
  - no_verify_ssl:
      value: 'true'
  - client_cert_location:
      value: "/root/clustera/admin.crt"
  - client_key_location:
      value: "/root/clustera/admin.key"
  - client_ca_cert_location:
      value: "/root/clustera/admin-ca.crt"
  - meth1:
      value: default
