---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - approval_type:
      value: noauto
  - InspectRequest:
      value: "/POC/Service/Provisioning/StateMachines/Request/InspectMe"
  - ValidateRequest:
      value: "/POC/Containers/Methods/ProjectRequestValidation"
      on_error: auto_fail_request
